clean execute_cmds_required_by_no_lock to avoid -Wthread-safety-analysis error (#800)
-Wthread-safety-analysis has been enabled in google infrastructure.
Thus clvk is failing:
```
third_party/clvk/src/queue.cpp:389:12: error: releasing mutex 'm_lock' that was not held [-Werror,-Wthread-safety-analysis]
  389 |     m_lock.unlock();
      |            ^
third_party/clvk/src/queue.cpp:395:1: error: mutex 'm_lock' is not held on every path through here [-Werror,-Wthread-safety-analysis]
  395 | }
      | ^
third_party/clvk/src/queue.cpp:392:12: note: mutex acquired here
  392 |     m_lock.lock();
      |            ^
2 errors generated.
```
This CL clean the usage of lock in execute_cmds_required_by_no_lock to
make it understandable by the compiler.